---
- name: Include OS-specific tasks
  include_tasks: "{{ ansible_facts['os_family'] | lower }}.yml"

# Open firewall for Apache 
- name: Open Apache port in firewall
  ufw:
    rule: allow
    port: "{{ Apache_port }}"
    proto: tcp
  when: firewall_enabled | default(false)

# Notify handlers
- name: Notify restart handler
  meta: flush_handlers
